### ISSUE TITLE
Part of a rss tag content being left out

### ISSUE THREAD

**Issue by Carbonhell** [manoelcampos/xml2lua#10]
Hello, I'm using this for a personal project regarding reading a rss feed in xml format, and it worked pretty nicely. Except a thing that i just noticed, i have this tag in particular:
`<updated>2018-05-24T23:17:11+02:00</updated>`
When i fetch it, and print the resulting string, it doesn't print the +02:00 part for some reasons. The result is:
2018-05-24T23:17:11
I'm not an expert, so I'm not sure if it's my fault or something.

**Comment by manoelcampos** [comment]
Could you please provide a very short example in a single Lua file (as in the How to Use Section), with a minimal XML that shows the issue?

**Comment by Carbonhell** [comment]
I'm sorry, after a few more tests I've noticed the error isn't with the parser, but with the string i passed it, which for some reasons deletes the data i need when i get it with a GET request from an URL. The parser itself works fine, thanks anyway!

**Comment by manoelcampos** [comment]
No problem.
