### ISSUE TITLE
Accessing children with index rather than name

### ISSUE THREAD

**Issue by slavidodo** [manoelcampos/xml2lua#18]
Ok, in pugixml you can easily do something like:
```for (pugi::xml_node& node : root.children()) { ... } ```

This is useful if you want the nodes in order.
My case is that i am using xml to handle some ui elements, so the order of the elements must be known in order to view them correctly.

```xml
<contents>
   <label>Some text</label>
   <image source="logo.png" />
   <textarea placeholder="..." />
   <label>Enjoying?</label>
</contents>
```

#### Current behaviour
```lua
root.contents.label -> table (n=2)
root.contents.image -> table (n=1)
root.contents.textarea -> table(n=1)
```

#### Expected behavior
```lua
-- same as above
-- also
root.children -> ordered children
```

This doesn't use more memory since tables in lua are actually passed by ref.
So children table will just have a reference to the original tables sorted by element name.

**Comment by slavidodo** [comment]
This is done already in the dom element.

**Comment by manoelcampos** [comment]
Maybe you got the order defined in the XML file just by change.
Lua [pairs function defines an arbitrary order to iterate over the table elements when they don't have a numbered index](https://www.lua.org/pil/19.3.html).
