### ISSUE TITLE
How to get the input xml value ?

### ISSUE THREAD

**Issue by wangpengli** [manoelcampos/xml2lua#26]
<?xml version="1.0"?>
<result>
  		<interpretation confidence="99">
    			<instance>abcd</instance>
    			<input mode="speech">1234 </input>
  		</interpretation>
</result>

in this case , with the xml2lua, how to get the input item's value , my means the "1234"?

**Comment by wangpengli** [comment]
`<?xml version="1.0"?>
<result>
  		<interpretation confidence="99">
    			<instance>123456789十1 23456789十123456789十1234567891</instance>
    			<input mode="speech">123456789十1 23456789十1212345678 </input>
  		</interpretation>
</result>`

**Comment by wangpengli** [comment]
`<?xml version="1.0"?>
<result>
  		<interpretation confidence="99">
    			<instance>abcd</instance>
    			<input mode="speech">1234 </input>
  		</interpretation>
</result>`

**Comment by manoelcampos** [comment]
Please check the available examples.
