### ISSUE TITLE
Can't parse `gl.xml`

### ISSUE THREAD

**Issue by v1993** [manoelcampos/xml2lua#31]
Tried to parse official OpenGL specifications and met a major problem: function names aren't preserved. Example to reproduce the problem:

```Lua
local xml2lua = require("xml2lua")
local handler = require("xmlhandler.tree")
local json = require 'json'

--local data = assert(io.open('gl.xml', 'r')):read('*a')
local data = '<proto>void <name>glEnableIndexedEXT</name></proto>'

local parser = xml2lua.parser(handler)
parser:parse(data)

print(json.encode(handler.root))
```

Result: `{"proto":"void"}`

**Comment by manoelcampos** [comment]
`<proto>void <name>glEnableIndexedEXT</name></proto>` is not a valid XML.

`void` is neither a tag, attribute or value.

**Comment by v1993** [comment]
Is it really invalid? XML validators report this as valid string and I highly doubt people would use invalid XML for such things. Other libraries (not for lua sadly) parse this well too.

**Comment by manoelcampos** [comment]
It may be valid, but at least it is a strange XML. Check issue #35. There may be XML parsers that accept this type of XML, but some such as Java parsers don't.

**Comment by manoelcampos** [comment]
Hey @v1993  
Check the latest release and PR #40.
Maybe it fixes your issue.

**Comment by v1993** [comment]
@manoelcampos No, my test code from the first message still fails with exactly same result. I've upgraded to xml2lua 1.3-5 using luarocks.

**Comment by manoelcampos** [comment]
It was just a try. Sorry that it doesn't work. But your xml doesn't have a common structure.
