### ISSUE TITLE
how to process international codepages / unicode ?

### ISSUE THREAD

**Issue by Micke3rd** [manoelcampos/xml2lua#32]
Hi Manoel,
I'm executing the embedded example "example4-table2xml.lua" in europe, where because of the different codepage, the row
`{_attr={type="legal"}, name="University of Brasília", city="Brasília-DF"}`
is wrong transformed to
`  <person type="legal">
    <city>Bras├¡lia-DF</city>
    <name>University of Bras├¡lia</name>
  </person>
`
The example file is utf encrypted, though the source shouldn't be the reason.
Any suggestions how I can solve it ?

thnx Micke

to deliver more examples
`local people = {
    person = {
        {_attr={type="natural"}, name="Micke", city="Aßlar"},
        {_attr={type="natural"}, name="Micke", city="MÜnchen"},
		{_attr={type="natural"}, name="Micke", city="AltÖtting"},
        {_attr={type="legal"}, name="University of Brasília", city="Brasília-DF"}
    }
}`
is wrong transformed to
`<people>
  <person type="natural">
    <city>A├ƒlar</city>
    <name>Micke</name>
  </person>
  <person type="natural">
    <city>M├£nchen</city>
    <name>Micke</name>
  </person>
  <person type="natural">
    <city>Alt├ûtting</city>
    <name>Micke</name>
  </person>
  <person type="legal">
    <city>Bras├¡lia-DF</city>
    <name>University of Bras├¡lia</name>
  </person>
</people>`

**Comment by manoelcampos** [comment]
Hello @Micke3rd 

It's very strange. UTF8 is exactly to avoid such issues. I checked that all files on the project are encoded with that charset. Which operating system and Lua version are you using?
