### ISSUE TITLE
Custom handler without endtag implementation fails to parse

### ISSUE THREAD

**Issue by DeltaF1** [manoelcampos/xml2lua#43]
Attempting to use a handler without an "endtag" method fails to pop the stack and results in an "Incomplete XML Document" error.

[This line](https://github.com/manoelcampos/xml2lua/blob/master/XmlParser.lua#L319)
```lua
            if table.remove(self._stack) ~= tag.name then
                err(self, string.format("%s (/%s)", self._errstr.unmatchedTagErr, tag.name), f.pos)
            end
```
should be moved outside of the `fexists` check so that the parser will still pop the stack properly.

(For context as to why a handler wouldn't implement endtag, I'm writing a handler to extract only the text nodes out of an XML document for my application)

**Comment by manoelcampos** [comment]
Sorry for the late reply.
In fact, the `endtag()` performs some additional processing, being a required function and the parsing doesn't work without it.
Try to explain your use case to see if I can help.
