### ISSUE TITLE
luarocks package build fail on 5.4 lua version

### ISSUE THREAD

**Issue by zhiburt** [manoelcampos/xml2lua#49]
Hey @manoelcampos it seems like the package may be updated?

```
sudo luarocks install --check-lua-versions xml2lua
xml2lua not found for Lua 5.4.
Checking if available for other Lua versions...
Checking for Lua 5.1...
Checking for Lua 5.2...
Checking for Lua 5.3...

Error: No results matching query were found for Lua 5.4.
xml2lua supports only Lua 5.1 and Lua 5.2 and Lua 5.3 but not Lua 5.4.
```

Thanks for the library.

**Comment by manoelcampos** [comment]
Thansk for reporting. Just fixed it. Check the new v1.4-2 version.

**Comment by humbertoperez-kr** [comment]
what is the resolution? what command I need to apply? please be more specific

**Comment by manoelcampos** [comment]
You just need to use the latest version.

**Comment by humbertoperez-kr** [comment]
would you mind to tech me how?

In the whole internet there is not correct information, I have a MacOS system

**Comment by manoelcampos** [comment]
You just have to follow the installation instructions at the README to download the latest version: 

```luarocks install xml2lua```
