### ISSUE TITLE
Is there any way to check a version of xml2lua in runtime?

### ISSUE THREAD

**Issue by lemniscati** [manoelcampos/xml2lua#54]
Thank you for development.

It would be happy for me if we can check a version of the module in runtime, in a way like:
```lua
m = require("xml2lua")
print ( m._VERSION )
```
cf. http://lua-users.org/wiki/ModuleVersioning

Regards,
Lem

**Comment by manoelcampos** [comment]
Hello @lemniscati 
I've just made the changes you suggested.
The code will work exactly as you showed.
Check the new 1.4-5 version.

Thanks for contributing.
