### ISSUE TITLE
xml2lua.toXml() is not parsing tag attributes correctly

### ISSUE THREAD

**Issue by evandrofisico** [manoelcampos/xml2lua#60]
Reading a existing XML file, parsing and outputting it sometimes still results in adding <_attr></_attr> instead of adding the attributes to the tag.
Example:
    local xml = xml2lua.loadFile(xmlfile)
    local parser = xml2lua.parser(handler)
    parser:parse(xml)
    print(xml2lua.toXml(handler.root))

In the input XML:
 <vcpu placement='static' >2</vcpu>

In the output XML:
          <vcpu>2</vcpu>
          <_attr>
              <placement>static</placement>
          </_attr>

[vm.xml.gz](https://github.com/manoelcampos/xml2lua/files/6686874/vm.xml.gz)

**Comment by manoelcampos** [comment]
It's just a printing issue, right?

**Comment by evandrofisico** [comment]
The generated table does have the _attr field, but it is moved and appears as a child node instead. So just reading a file, parsing it as a table and outputting it produces a different (and invalid) xml from the original. I believe the expected behavior would be that reading, parsing and outputting should produce the same data as the input, right?
Attached are a sample program and xml file showing the behaviour.
[bug.tar.gz](https://github.com/manoelcampos/xml2lua/files/6785288/bug.tar.gz)

**Comment by manoelcampos** [comment]
You're right. I take a look at it. Thanks for reporting.

**Comment by manoelcampos** [comment]
I used a smaller XML to make it easier to debug.

```xml
<?xml version="1.0"?>
<domain type="xen">
  <on_crash>restart</on_crash>
  <clock offset="utc" adjustment="reset"/>
  <memory unit="KiB">16777216</memory>
</domain>
```

**Comment by manoelcampos** [comment]
Could you please use the version in #61 and let me know if it works for your scenario?
