### ISSUE TITLE
toXml got different result between 1.5-1 and 1.5-2

### ISSUE THREAD

**Issue by yanxianrui** [manoelcampos/xml2lua#63]
Hello, thanks for nice work. 

example4-table2xml.lua in 1.5-1  got result as follows

`XML Representation
<people>
    <person type="natural">
      <city>Palmas-TO</city>
      <name>Manoel</name>
    </person>
    <person type="natural">
      <city>Palmas-TO</city>
      <name>Breno</name>
    </person>
    <person type="legal">
      <city>Brasília-DF</city>
      <name>University of Brasília</name>
    </person>
</people>`

while got different one as 

`XML Representation
<people>
    <person>
      <person type="natural">
        <city>Palmas-TO</city>
        <name>Manoel</name>
      </person>
      <person type="natural">
        <city>Palmas-TO</city>
        <name>Breno</name>
      </person>
      <person type="legal">
        <city>Brasília-DF</city>
        <name>University of Brasília</name>
      </person>
    </person>
</people>`    

in 1.5-2

Is this a feature of the new version?

**Comment by manoelcampos** [comment]
Thanks for reporting. The example passed the name for a surrounding tag when calling xml2lua.toXml(). That is not needed anymore. Them, the example was just updated. Thanks for reporting.
