### ISSUE TITLE
How to install with ZeroBraneStudio?

### ISSUE THREAD

**Issue by FiftyTifty** [manoelcampos/xml2lua#71]
The instructions aren't exactly comprehensive. It's no more than "Get LuaRocks, and install via LuaRocks". But that's a mess, when you are not using LuaRocks.

ZBS Uses LuaDist as a package manager, and has a couple of caveats. How would I install XML2Lua for ZBS?

**Comment by manoelcampos** [comment]
I've never even heard about LuaDist. If you just place the lib files inside your project (following the same directory structure) it will probably work right away. 

It doesn't matter what IDE or editor you are using, you don't need them to install the lib using LuaRocks, the instructions above, or any other method that I'm not aware of.

By the way, PRs are welcome.

**Comment by ferdnyc** [comment]
@manoelcampos I wouldn't worry about it: LuaDist [is entirely abandoned](https://github.com/LuaDist/luadist.github.com/commit/cc297b56274740341cca52c8c5b05a83a119491d) at this point, with all of its repos archived and a banner across the top of the [luadist.org](luadist.org) landing page reading:

![image](https://user-images.githubusercontent.com/538020/147377779-88e3c160-86dc-4891-b459-9ce79412a3ac.png)

Looks like ZBS needs to get with the times. (Or @FiftyTifty just needs to install luarocks, which is as easy as the instructions found at https://luarocks.org/#quick-start):
```sh
$ wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz
$ tar zxpf luarocks-3.8.0.tar.gz
$ cd luarocks-3.8.0
$ ./configure && make && sudo make install
```

**Comment by manoelcampos** [comment]
Great, thanks @ferdnyc
