### ISSUE TITLE
Creating a DOM tree is missing XML declaration

### ISSUE THREAD

**Issue by geert56** [manoelcampos/xml2lua#79]
Any XML declaration gets lost when parsing XML. Also, a ROOT type node is never created when using
the DOM handler.
As I understand it, the first tree node should be of type ROOT and when present should have the XML declaration as a child node under the DECL type. The first start element would then be the second child.
This is easy to fix in xmlhandler/dom.lua in the function dom:decl() by adding:
	if self.root == nil then
	  self.root = self.current
	end
before or after the table.insert.

On reflection, I think it is even better to always have a ROOT node in the DOM handler, so that top-level comments are also preserved as its children. This can be achieved by setting root=curent in the init() function.

**Comment by doj** [comment]
I've seen https://github.com/manoelcampos/xml2lua/compare/master...Tekenlight:xml2lua:master which may be a similar fix.

**Comment by doj** [comment]
yes, I've noticed that at well. Also any DTD node is lost with the DOM handler.
I've fixed that in my branch https://github.com/doj/xml2lua/tree/dom-fixes where I do create a ROOT node, which would contain the DECL node, DTD node and the root ELEMENT node.

**Comment by manoelcampos** [comment]
Hello guys. I'm not being able to maintain this project and I'm looking for a maintainer that can take over it.
