### ISSUE TITLE
Cant use equal sign in attributes

### ISSUE THREAD

**Issue by crea-Tec** [manoelcampos/xml2lua#8]
Hi manoel,
thanks for your good work.
If I try to use equal signs as a part of attributes, so I receive a failure as shown below:

> part of my .xml

```xml
<BasicType Name="Some tag name">
     <String Length="10" FixedLength="True" DefaultValue="Tag1=" />
</BasicType>
```
 

> output

`
Exception in thread "main" com.naef.jnlua.LuaRuntimeException: ...\src\xml2lua.lua:268: Unbalanced Tag (/BasicType) [char=5871]
`

Is there a work around for this case?

[My Version](https://github.com/manoelcampos/xml2lua/tree/v1.0-1)

**Comment by manoelcampos** [comment]
Hi @crea-Tec 
Try the latest release 1.1-1, but probably it has the same issue.
I'll take a look at it by the end of the week.
Thanks for reporting.

**Comment by manoelcampos** [comment]
Hi @crea-Tec 
I've just fixed the issue. Download the new version using luarocks. 
Thanks for reporting.

**Comment by crea-Tec** [comment]
Thank you for this.
