### ISSUE TITLE
Xml contains Chinese, which will become garbled 

### ISSUE THREAD

**Issue by setcurl** [manoelcampos/xml2lua#91]
This bug is annoying, can you fix it? 
![Screenshot_2023-03-19-13-32-58-437_com jesse205 androlua androidX material3](https://user-images.githubusercontent.com/78637344/226157339-814b2b2c-62ce-46e0-84d1-5e742060ef31.png)

**Comment by wenlifan** [comment]
中文乱码是自带print.lua 导致的，用自己项目的log库就可以了嘛！

**Comment by manoelcampos** [comment]
Closing due to lack of context and detailed information.
